// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {p2p} from '../models';

export function GetPeers():Promise<Array<string>>;

export function SendFileChunk(arg1:p2p.FileChunk):Promise<boolean>;

export function StartFileTransfer(arg1:p2p.FileInfo):Promise<boolean>;
