// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {p2p} from '../models';

export function AuthorizePeer(arg1:string):Promise<boolean>;

export function CancelSession(arg1:p2p.SessionCancel):Promise<void>;

export function GetPeers():Promise<Array<string>>;

export function RequestSessionAuth(arg1:p2p.SessionInfo):Promise<void>;

export function SendFileChunk(arg1:p2p.TransferChunk):Promise<void>;

export function SignalSessionCompletion(arg1:string,arg2:number):Promise<void>;
