// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function SendCancelSignal(arg1) {
  return window['go']['main']['App']['SendCancelSignal'](arg1);
}

export function SendFileChunk(arg1) {
  return window['go']['main']['App']['SendFileChunk'](arg1);
}

export function StartFileTransfer(arg1) {
  return window['go']['main']['App']['StartFileTransfer'](arg1);
}
