// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSession(arg1) {
  return window['go']['main']['App']['CancelSession'](arg1);
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function RequestSessionAuth(arg1) {
  return window['go']['main']['App']['RequestSessionAuth'](arg1);
}

export function SendFileChunk(arg1) {
  return window['go']['main']['App']['SendFileChunk'](arg1);
}
