// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthorizePeer(arg1) {
  return window['go']['main']['App']['AuthorizePeer'](arg1);
}

export function CancelSession(arg1) {
  return window['go']['main']['App']['CancelSession'](arg1);
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function RequestSessionAuth(arg1) {
  return window['go']['main']['App']['RequestSessionAuth'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDowloadFolder() {
  return window['go']['main']['App']['SelectDowloadFolder']();
}

export function SendFileChunk(arg1) {
  return window['go']['main']['App']['SendFileChunk'](arg1);
}

export function SignalSessionCompletion(arg1, arg2) {
  return window['go']['main']['App']['SignalSessionCompletion'](arg1, arg2);
}
